(function(){var n=this,aa=function(a,b,c){return a.call.apply(a.bind,arguments)},ba=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},q=function(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return q.apply(null,arguments)};var t=(new Date).getTime();var w=function(a){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a},ca=function(a,b){var c=parseInt(a,10);return isNaN(c)?b:c},x=function(a,b){return/^true$/.test(a)?!0:/^false$/.test(a)?!1:b},da=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,ea=function(a,b){if(!a)return b;var c=a.match(da);return c?c[0]:b};var fa=w("0.15"),ga=w("0.01"),ha=w("0.001"),sa=ca("101",-1),ta=ca("10",0),ua=w("0.05"),va=w("0.001"),wa=w("0"),xa=w("0.001"),ya=w("0.001"),
za=w("0.2"),Aa=x("true",!0),Ba=w("0.01"),Ca=w("0.03"),Da=w("0.001"),Ea=w("0.01");var Fa=function(){return"r20150922"},Ga=x("false",!1),Ha=x("false",!1),Ia=x("false",!1),Ja=Ia||!Ha;var Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},db=/&/g,eb=/</g,fb=/>/g,gb=/"/g,hb=/'/g,ib=/\x00/g,jb={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},A={"'":"\\'"},kb=function(a,b){return a<b?-1:a>b?1:0};var F=function(a){F[" "](a);return a};F[" "]=function(){};var G;a:{var lb=n.navigator;if(lb){var mb=lb.userAgent;if(mb){G=mb;break a}}G=""};var nb=-1!=G.indexOf("Opera")||-1!=G.indexOf("OPR"),H=-1!=G.indexOf("Trident")||-1!=G.indexOf("MSIE"),ob=-1!=G.indexOf("Edge"),I=-1!=G.indexOf("Gecko")&&!(-1!=G.toLowerCase().indexOf("webkit")&&-1==G.indexOf("Edge"))&&!(-1!=G.indexOf("Trident")||-1!=G.indexOf("MSIE"))&&-1==G.indexOf("Edge"),pb=-1!=G.toLowerCase().indexOf("webkit")&&-1==G.indexOf("Edge"),qb=function(){var a=G;if(I)return/rv\:([^\);]+)(\)|;)/.exec(a);if(ob)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);
if(pb)return/WebKit\/(\S+)/.exec(a)},rb=function(){var a=n.document;return a?a.documentMode:void 0},sb=function(){if(nb&&n.opera){var a;var b=n.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=qb())&&(a=b?b[1]:"");return H&&(b=rb(),b>parseFloat(a))?String(b):a}(),tb={},ub=function(a){if(!tb[a]){for(var b=0,c=Ka(String(sb)).split("."),d=Ka(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",h=RegExp("(\\d*)(\\D*)","g"),u=RegExp("(\\d*)(\\D*)","g");
do{var p=h.exec(g)||["","",""],m=u.exec(k)||["","",""];if(0==p[0].length&&0==m[0].length)break;b=kb(0==p[1].length?0:parseInt(p[1],10),0==m[1].length?0:parseInt(m[1],10))||kb(0==p[2].length,0==m[2].length)||kb(p[2],m[2])}while(0==b)}tb[a]=0<=b}},vb=n.document,wb=vb&&H?rb()||("CSS1Compat"==vb.compatMode?parseInt(sb,10):5):void 0;var xb;if(!(xb=!I&&!H)){var yb;if(yb=H)yb=9<=wb;xb=yb}xb||I&&ub("1.9.1");H&&ub("9");var N=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)};var zb=function(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{F(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(d){return!1}},O=function(a,b){if(!(1E-4>Math.random())){var c=Math.random();if(c<b)return c=Ab(window),a[Math.floor(c*a.length)]}return null},Ab=function(a){try{var b=new Uint32Array(1);a.crypto.getRandomValues(b);return b[0]/65536/65536}catch(c){return Math.random()}},Bb=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)};var Eb=function(a,b,c,d,e,f){try{if((d?a.X:Math.random())<(e||a.N)){var g=a.M+b+Cb(c),g=g.substring(0,2E3);"undefined"===typeof f?Db(g):Db(g,f)}}catch(k){}},Cb=function(a){var b="";Bb(a,function(a,d){if(0===a||a)b+="&"+d+"="+encodeURIComponent(String(a))});return b},Db=function(a,b){n.google_image_requests||(n.google_image_requests=[]);var c=n.document.createElement("img");if(b){var d=function(a){b(a);a=d;c.removeEventListener?c.removeEventListener("load",a,!1):c.detachEvent&&c.detachEvent("onload",
a);a=d;c.removeEventListener?c.removeEventListener("error",a,!1):c.detachEvent&&c.detachEvent("onerror",a)};N(c,"load",d);N(c,"error",d)}c.src=a;n.google_image_requests.push(c)};var P=window,Fb,Gb=null,Hb=document.getElementsByTagName("script");Hb&&Hb.length&&(Gb=Hb[Hb.length-1]);Fb=Gb;var Ib=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(null,a[c],c,a)},Jb=function(a){return!!a&&"function"==typeof a&&!!a.call},Kb=function(a,b){if(!(2>arguments.length))for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c])},Lb=function(a,b){if(a.indexOf){var c=a.indexOf(b);return 0<c||0===c}for(c=0;c<a.length;c++)if(a[c]===b)return!0;return!1},Mb=function(a,b){N(a,"load",b)},Nb=function(a){"google_onload_fired"in a||(a.google_onload_fired=!1,Mb(a,function(){a.google_onload_fired=
!0}))},Ob=function(){var a=P.google_unique_id;return"number"==typeof a?a:0},Pb=function(a){var b=a.length;if(0==b)return 0;for(var c=305419896,d=0;d<b;d++)c^=(c<<5)+(c>>2)+a.charCodeAt(d)&4294967295;return 0<c?c:4294967296+c},Qb=!!window.google_async_iframe_id;var Rb=function(a){return(a=a.google_ad_modifications)?a.loeids||[]:[]},Sb=function(a,b,c){if(!a)return null;for(var d=0;d<a.length;++d)if((a[d].ad_slot||b)==b&&(a[d].ad_tag_origin||c)==c)return a[d];return null};var Tb=function(a,b,c){this.U=a;this.P=b;this.w=c;this.v=null;this.O=this.o;this.ca=!1},Ub=function(a,b,c){this.message=a;this.fileName=b||"";this.lineNumber=c||-1},Wb=function(a,b,c,d){var e;try{e=c()}catch(f){var g=a.w;try{var k=Vb(f),g=(d||a.O).call(a,b,k,void 0,void 0)}catch(h){a.o("pAR",h)}if(!g)throw f;}finally{}return e},Xb=function(a,b){var c=Q;return function(){var d=arguments;return Wb(c,a,function(){return b.apply(void 0,d)})}};
Tb.prototype.o=function(a,b,c,d,e){var f={};f.context=a;b instanceof Ub||(b=Vb(b));f.msg=b.message.substring(0,512);b.fileName&&(f.file=b.fileName);0<b.lineNumber&&(f.line=b.lineNumber.toString());a=n.document;f.url=a.URL.substring(0,512);f.ref=a.referrer.substring(0,512);if(this.v)try{this.v(f)}catch(g){}if(d)try{d(f)}catch(k){}Eb(this.U,e||this.P,f,this.ca,c);return this.w};
var Vb=function(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){var c=a.stack,d=b;try{-1==c.indexOf(d)&&(c=d+"\n"+c);for(var e;c!=e;)e=c,c=c.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=c.replace(/\n */g,"\n")}catch(f){b=d}}return new Ub(b,a.fileName,a.lineNumber)};var Yb,Q,Zb="http"+("http:"==P.location.protocol?"":"s")+"://pagead2.googlesyndication.com/pagead/gen_204?id=";Yb=new function(){this.M=Zb;this.N=.01;this.X=Math.random()};Q=new Tb(Yb,"jserror",!0);var Hc=function(a,b){Wb(Q,a,b,Gc)},Gc=Q.o,Ic=function(a,b){return Xb(a,b)};var Jc={client:"google_ad_client",format:"google_ad_format",slotname:"google_ad_slot",output:"google_ad_output",ad_type:"google_ad_type",async_oa:"google_async_for_oa_experiment",dimpr:"google_always_use_delayed_impressions_experiment",peri:"google_top_experiment",pse:"google_pstate_expt"};Q.w=!Ga;Q.v=function(a){a.shv=Fa();Bb(Jc,function(b,c){try{null!=n[b]&&(a[c]=n[b])}catch(d){}})};var Kc=null,Lc=function(){if(!Kc){for(var a=window,b=a,c=0;a&&a!=a.parent;)if(a=a.parent,c++,zb(a))b=a;else break;Kc=b}return Kc};var V={ea:{j:"17415661",i:"17415662"},Ba:{j:"453848100",i:"453848101"},na:{j:"828064124",i:"828064125"},ma:{j:"828064127",i:"828064128"},oa:{j:"828064170",i:"828064171"},ga:{j:"453848130",i:"453848131",za:"453848132",Aa:"453848133"},ra:{j:"24819308",i:"24819309",fa:"24819320"},qa:{j:"24819330",i:"24819331"},ta:{j:"828064162",i:"828064163"},sa:{j:"828064164",i:"828064165",ia:"828064166"},la:{j:"828064190",i:"828064191"},va:{j:"10573503",i:"10573504"},J:{j:"10573593",i:"10573594"},ya:{j:"10573511",
i:"10573512"},L:{j:"10573581",i:"10573582"},ja:{j:"10573521",i:"10573522"},H:{j:"10573571",i:"10573572"},wa:{j:"10573531",i:"10573532"},K:{j:"10573561",i:"10573562"},xa:{j:"10573551",i:"10573552"},pa:{j:24819400,i:24819401},ua:{j:"312815000",i:"312815001"},I:{j:"312815100",i:"312815101"},ha:{j:"26835101",i:"26835102"},ka:{j:"35923720",i:"35923721"},A:{j:"35923760",i:"35923761"}};var Mc=function(a,b){this.start=a<b?a:b;this.end=a<b?b:a};var Nc=function(a){var b;try{b=parseInt(a.localStorage.getItem("google_experiment_mod"),10)}catch(c){return null}if(0<=b&&1E3>b)return b;b=Math.floor(1E3*Ab(a));try{return a.localStorage.setItem("google_experiment_mod",""+b),b}catch(d){return null}};var Oc=new function(){this.V=new Mc(100,199)};var W=function(a,b,c,d){return a.location&&a.location.hash=="#google_plle_"+d?d:O([c,d],b)};var Pc=function(a,b,c){Hc("files::getSrc",function(){if("https:"==P.location.protocol&&"http"==c)throw c="https",Error("Requested url "+a+b);});return[c,"://",a,b].join("")},Qc=function(a,b,c){c||(c=Ja?"https":"http");return Pc(a,b,c)};var Rc=function(){},Tc=function(a,b,c){switch(typeof b){case "string":Sc(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(b instanceof Array||void 0!=b.length&&b.splice){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),Tc(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)b.hasOwnProperty(e)&&(f=b[e],"function"!=typeof f&&(c.push(d),Sc(e,
c),c.push(":"),Tc(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}},Uc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Vc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,Sc=function(a,b){b.push('"');b.push(a.replace(Vc,function(a){if(a in Uc)return Uc[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Uc[a]=e+b.toString(16)}));
b.push('"')};var Wc=null,Xc=I||pb||nb||"function"==typeof n.atob;var Yc="google_ad_block google_ad_channel google_ad_client google_ad_format google_ad_height google_ad_host google_ad_host_channel google_ad_host_tier_id google_ad_modifications google_ad_output google_ad_region google_ad_section google_ad_slot google_ad_type google_ad_unit_key google_ad_unit_key_2 google_ad_width google_adtest google_allow_expandable_ads google_alternate_ad_url google_alternate_color google_analytics_domain_name google_analytics_uacct google_analytics_url_parameters google_available_width google_captcha_token google_city google_color_bg google_color_border google_color_line google_color_link google_color_text google_color_url google_container_id google_content_recommendation_ui_type google_contents google_core_dbp google_country google_cpm google_ctr_threshold google_cust_age google_cust_ch google_cust_criteria google_cust_gender google_cust_id google_cust_interests google_cust_job google_cust_l google_cust_lh google_cust_u_url google_disable_video_autoplay google_ed google_eids google_ember_h google_ember_w google_enable_content_recommendations google_enable_ose google_enable_ose_periscope google_encoding google_floating_ad_position google_font_face google_font_size google_frame_id google_gl google_hints google_is_split_slot google_image_size google_kw google_kw_type google_lact google_language google_loeid google_max_num_ads google_max_radlink_len google_mtl google_nofo google_num_radlinks google_num_radlinks_per_unit google_only_ads_with_video google_only_pyv_ads google_only_userchoice_ads google_override_format google_page_url google_pgb_reactive google_previous_watch google_previous_searches google_referrer_url google_region google_responsive_formats google_reuse_colors google_rl_dest_url google_rl_filtering google_rl_mode google_rt google_safe google_scs google_source_type google_sui google_skip google_tag_for_child_directed_treatment google_tag_info google_tag_origin google_tdsma google_tfs google_tl google_ui_features google_video_doc_id google_video_product_type google_video_url_to_fetch google_webgl_support google_with_pyv_ads google_yt_pt google_yt_up".split(" "),
Zc={google_ad_modifications:!0,google_analytics_domain_name:!0,google_analytics_uacct:!0},$c=function(a){return(a=a.innerText||a.innerHTML)&&(a=a.replace(/^\s+/,"").split(/\r?\n/,1)[0].match(/^\x3c!--+(.*?)(?:--+>)?\s*$/))&&/google_ad_client/.test(a[1])?a[1]:null},ad=function(a){if(a=a.innerText||a.innerHTML)if(a=a.replace(/^\s+/,"").split(/\r?\n/,1)[0],(a=a.match(/^\x3c!--+(.*?)(?:--+>)?\s*$/)||a.match(/^\/*\s*<!\[CDATA\[(.*?)(?:\/*\s*\]\]>)?\s*$/i))&&/google_ad_client/.test(a[1]))return a[1];return null},
bd=function(a){if(a=a.innerText||a.innerHTML)if(a=a.replace(/^\s+|\s+$/g,"").replace(/\s*(\r?\n)+\s*/g,";"),(a=a.match(/^\x3c!--+(.*?)(?:--+>)?$/)||a.match(/^\/*\s*<!\[CDATA\[(.*?)(?:\/*\s*\]\]>)?$/i))&&/google_ad_client/.test(a[1]))return a[1];return null},ed=function(a,b){var c;try{a:{var d=a.document.getElementsByTagName("script"),e=$c,f;"undefined"!=typeof a.google_pubvars_recovery_regexp_experiment?f=a.google_pubvars_recovery_regexp_experiment:(f=O(["C","E","EM"],Ca),a.google_pubvars_recovery_regexp_experiment=
f);b.google_pubvars_recovery_regexp_experiment=f;switch(f){case "E":e=ad;break;case "EM":e=bd}for(var g=d.length-1;0<=g;g--){var k=d[g];if(!k.google_parsed_script){k.google_parsed_script=!0;var h=e(k);if(h){c=h;break a}}}c=null}}catch(u){return!1}if(!c)return!1;try{for(var d=/(google_\w+) *= *(['"]?[\w.-]+['"]?) *(?:;|$)/gm,e={},p;p=d.exec(c);)e[p[1]]=cd(p[2]);dd(e,a)}catch(m){return!1}return!!a.google_ad_client},fd=function(a){a.google_page_url&&(a.google_page_url=String(a.google_page_url));var b=
[];Ib(a,function(a,d){if(null!=a){var e;try{var f=[];Tc(new Rc,a,f);e=f.join("")}catch(g){}e&&(e=e.replace(/\//g,"\\$&"),Kb(b,d,"=",e,";"))}});return b.join("")},gd=function(a){for(var b=0,c=Yc.length;b<c;b++){var d=Yc[b];Zc[d]||(a[d]=null)}},cd=function(a){switch(a){case "true":return!0;case "false":return!1;case "null":return null;case "undefined":break;default:try{var b=a.match(/^(?:'(.*)'|"(.*)")$/);if(b)return b[1]||b[2]||"";if(/^[-+]?\d*(\.\d+)?$/.test(a)){var c=parseFloat(a);return c===c?c:
void 0}}catch(d){}}},dd=function(a,b){for(var c=0;c<Yc.length;c++){var d=Yc[c];null==b[d]&&null!=a[d]&&(b[d]=a[d])}};var hd=null;var id=function(a){this.m=a;a.google_iframe_oncopy||(a.google_iframe_oncopy={handlers:{},upd:q(this.ba,this)});this.Z=a.google_iframe_oncopy},jd;var X="var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}";
/[\x00&<>"']/.test(X)&&(-1!=X.indexOf("&")&&(X=X.replace(db,"&amp;")),-1!=X.indexOf("<")&&(X=X.replace(eb,"&lt;")),-1!=X.indexOf(">")&&(X=X.replace(fb,"&gt;")),-1!=X.indexOf('"')&&(X=X.replace(gb,"&quot;")),-1!=X.indexOf("'")&&(X=X.replace(hb,"&#39;")),-1!=X.indexOf("\x00")&&(X=X.replace(ib,"&#0;")));jd=X;id.prototype.set=function(a,b){this.Z.handlers[a]=b;this.m.addEventListener&&this.m.addEventListener("load",q(this.R,this,a),!1)};
id.prototype.R=function(a){a=this.m.document.getElementById(a);try{var b=a.contentWindow.document;if(a.onload&&b&&(!b.body||!b.body.firstChild))a.onload()}catch(c){}};id.prototype.ba=function(a,b){var c=kd("rx",a),d;a:{if(a&&(d=a.match("dt=([^&]+)"))&&2==d.length){d=d[1];break a}d=""}d=(new Date).getTime()-d;c=c.replace(/&dtd=(\d+|M)/,"&dtd="+(1E4>d?d+"":"M"));this.set(b,c);return c};var kd=function(a,b){var c=new RegExp("\\b"+a+"=(\\d+)"),d=c.exec(b);d&&(b=b.replace(c,a+"="+(+d[1]+1||1)));return b};var ld=/MSIE [2-7]|PlayStation|Gecko\/20090226|Android 2\.|Opera/i,md=/Android/,nd=!1;var od=function(a){if(!a)return"";(a=a.toLowerCase())&&"ca-"!=a.substring(0,3)&&(a="ca-"+a);return a};var pd={"120x90":!0,"160x90":!0,"180x90":!0,"200x90":!0,"468x15":!0,"728x15":!0};var qd="google_ad_client google_ad_format google_ad_height google_ad_width google_city google_country google_encoding google_language google_page_url".split(" "),rd=function(a){try{var b=a.top.google_ads_params_store;if(b)return b;b=a.top.google_ads_params_store={};if(b===a.top.google_ads_params_store)return b}catch(c){}return null};var Y,Z=function(a){this.u=[];this.m=a||window;this.l=0;this.s=null;this.G=0},sd=function(a,b){this.S=a;this.da=b};Z.prototype.enqueue=function(a,b){0!=this.l||0!=this.u.length||b&&b!=window?this.C(a,b):(this.l=2,this.F(new sd(a,window)))};Z.prototype.C=function(a,b){this.u.push(new sd(a,b||this.m));td(this)};Z.prototype.T=function(a){this.l=1;if(a){var b=Ic("sjr::timeout",q(this.D,this,!0));this.s=this.m.setTimeout(b,a)}};
Z.prototype.D=function(a){a&&++this.G;1==this.l&&(null!=this.s&&(this.m.clearTimeout(this.s),this.s=null),this.l=0);td(this)};Z.prototype.Y=function(){return!(!window||!Array)};Z.prototype.$=function(){return this.G};Z.prototype.nq=Z.prototype.enqueue;Z.prototype.nqa=Z.prototype.C;Z.prototype.al=Z.prototype.T;Z.prototype.rl=Z.prototype.D;Z.prototype.sz=Z.prototype.Y;Z.prototype.tc=Z.prototype.$;var td=function(a){var b=Ic("sjr::tryrun",q(a.aa,a));a.m.setTimeout(b,0)};
Z.prototype.aa=function(){if(0==this.l&&this.u.length){var a=this.u.shift();this.l=2;var b=Ic("sjr::run",q(this.F,this,a));a.da.setTimeout(b,0);td(this)}};Z.prototype.F=function(a){this.l=0;a.S()};
var ud=function(a){try{return a.sz()}catch(b){return!1}},vd=function(a){return!!a&&("object"==typeof a||"function"==typeof a)&&ud(a)&&Jb(a.nq)&&Jb(a.nqa)&&Jb(a.al)&&Jb(a.rl)},wd=function(){if(Y&&ud(Y))return Y;var a=Lc(),b=a.google_jobrunner;return vd(b)?Y=b:a.google_jobrunner=Y=new Z(a)},xd=function(a,b){wd().nq(a,b)},yd=function(a,b){wd().nqa(a,b)};var zd=Qb?1==Ob():!Ob(),Ad=function(){var a=Ia?"https":"http",b=F("script"),c;c=ea("","pagead2.googlesyndication.com");return["<",b,' src="',Qc(c,["/pagead/js/",Fa(),"/r20150820/show_ads_impl.js"].join(""),a),'"></',b,">"].join("")},Bd=function(a,b,c,d){return function(){var e=!1;d&&wd().al(3E4);var f=a.document.getElementById(b);f&&!zb(f.contentWindow)&&
3==a.google_top_js_status&&(a.google_top_js_status=6);try{var g=a.document.getElementById(b).contentWindow;if(zb(g)){var k=a.document.getElementById(b).contentWindow,h=k.document;h.body&&h.body.firstChild||(h.open(),k.google_async_iframe_close=!0,h.write(c))}else{var u=a.document.getElementById(b).contentWindow,p;f=c;f=String(f);if(f.quote)p=f.quote();else{g=['"'];for(k=0;k<f.length;k++){var m=f.charAt(k),B=m.charCodeAt(0),h=g,R=k+1,J;if(!(J=jb[m])){var C;if(31<B&&127>B)C=m;else{var y=m;if(y in A)C=
A[y];else if(y in jb)C=A[y]=jb[y];else{var v=y,z=y.charCodeAt(0);if(31<z&&127>z)v=y;else{if(256>z){if(v="\\x",16>z||256<z)v+="0"}else v="\\u",4096>z&&(v+="0");v+=z.toString(16).toUpperCase()}C=A[y]=v}}J=C}h[R]=J}g.push('"');p=g.join("")}u.location.replace("javascript:"+p)}e=!0}catch(K){u=Lc().google_jobrunner,vd(u)&&u.rl()}e&&(e=kd("google_async_rrc",c),(new id(a)).set(b,Bd(a,b,e,!1)))}},Cd=function(a){var b=["<iframe"];Ib(a,function(a,d){null!=a&&b.push(" "+d+'="'+a+'"')});b.push("></iframe>");return b.join("")},
Dd=function(a){var b;if(b=zd){if(!hd)a:{var c=[P.top];b=[];for(var d=0,e;e=c[d++];){b.push(e);try{if(e.frames)for(var f=e.frames.length,g=0;g<f&&1024>c.length;++g)c.push(e.frames[g])}catch(k){}}for(f=0;f<b.length;f++)try{var h=b[f].frames.google_esf;if(h){hd=h;break a}}catch(u){}hd=null}b=!hd}return b?(h={style:"display:none"},h["data-ad-client"]=od(a),h.id="google_esf",h.name="google_esf",a=Qc(ea("","googleads.g.doubleclick.net"),["/pagead/html/",Fa(),"/r20150820/zrt_lookup.html"].join("")),
h.src=a,Cd(h)):""},Fd=function(a,b,c){var d=b.google_ad_output,e=b.google_ad_format;e||"html"!=d&&null!=d||(e=b.google_ad_width+"x"+b.google_ad_height,c&&(e+="_as"),b.google_ad_format_suffix&&(e+=b.google_ad_format_suffix));c=!b.google_ad_slot||Ed(b);e=e&&c?e.toLowerCase():"";b.google_ad_format=e;e=[b.google_ad_slot,b.google_ad_format,b.google_ad_type,b.google_ad_width,b.google_ad_height];c=[];for(var d=0,f=Fb.parentElement;f&&25>d;f=f.parentNode,++d)c.push(9!=f.nodeType&&f.id||"");(c=c.join())&&
e.push(c);b.google_ad_unit_key=Pb(e.join(":")).toString();e=a.google_adk2_experiment=a.google_adk2_experiment||O(["C","E"],ya)||"N";if("E"==e){e=Fb;c=[];for(d=0;e&&25>d;++d){var f="",f=(f=9!=e.nodeType&&e.id)?"/"+f:"",g;a:{if(e&&e.nodeName&&e.parentElement){g=e.nodeName.toString().toLowerCase();for(var k=e.parentElement.childNodes,h=0,u=0;u<k.length;++u){var p=k[u];if(p.nodeName&&p.nodeName.toString().toLowerCase()==g){if(e==p){g="."+h;break a}++h}}}g=""}c.push((e.nodeName&&e.nodeName.toString().toLowerCase())+
f+g);e=e.parentElement}e=c.join()+":";c=[];if(a)try{for(var m=a.parent,d=0;m&&m!=a&&25>d;++d){for(var B=m.frames,f=0;f<B.length;++f)if(a==B[f]){c.push(f);break}a=m;m=a.parent}}catch(R){}b.google_ad_unit_key_2=Pb(e+c.join()).toString()}else"C"==e&&(b.google_ad_unit_key_2="ctrl")},Gd=Math.floor(1E6*Math.random()),Hd=function(a){var b;try{b={};for(var c=a.data.split("\n"),d=0;d<c.length;d++){var e=c[d].indexOf("=");-1!=e&&(b[c[d].substr(0,e)]=c[d].substr(e+1))}}catch(f){}c=b[3];if(b[1]==Gd&&(window.google_top_js_status=
4,a.source==top&&0==c.indexOf(a.origin)&&(window.google_top_values=b,window.google_top_js_status=5),window.google_top_js_callbacks)){for(a=0;a<window.google_top_js_callbacks.length;a++)window.google_top_js_callbacks[a]();window.google_top_js_callbacks.length=0}},Ed=function(a){return a.google_override_format||!pd[a.google_ad_width+"x"+a.google_ad_height]&&"aa"==a.google_loader_used};Hc("sa::main",function(){var a=window,b=a.google_ad_modifications=a.google_ad_modifications||{};if(!b.plle){b.plle=!0;var c=b.loeids=b.loeids||[],d=V.J,e,f=d.i,g;if(a.location&&a.location.hash=="#google_plle_"+f)g=f;else{var k=[d.j,f],h=new Mc(sa,sa+ta-1),u;if(!(u=0>=ta||ta%k.length)){var p=Oc.V;u=!(p.start<=h.start&&p.end>=h.end)}if(u)g=null;else{var m=Nc(a);g=null!==m&&h.start<=m&&h.end>=m?k[(m-sa)%k.length]:null}}(e=g)&&c.push(e);var d=V.I,B=W(a,ua,d.j,d.i);B&&c.push(B);var d=V.L,R=W(a,va,d.j,
d.i);R&&c.push(R);var d=V.H,J=W(a,wa,d.j,d.i);J&&c.push(J);var d=V.K,C=W(a,xa,d.j,d.i);C&&c.push(C);var d=V.A,y=W(a,Ea,d.j,d.i);y&&c.push(y)}var v;var z=a.google_ad_slot,K=a.google_ad_modifications;if(!K||Sb(K.ad_whitelist,z,void 0))v=null;else{var $b=K.space_collapsing||"none",ac=Sb(K.ad_blacklist,z);v=ac?{B:!0,W:ac.space_collapsing||$b}:K.remove_ads_by_default?{B:!0,W:$b}:null}if(v&&v.B)gd(a);else{Nb(a);if(!window.google_top_experiment&&!window.google_top_js_status){var La=window;if(2!==(La.top==
La?0:zb(La.top)?1:2))window.google_top_js_status=0;else if(top.postMessage){var Ma;try{Ma=P.top.frames.google_top_static_frame?!0:!1}catch(Yd){Ma=!1}if(Ma){if(window.google_top_experiment=O(["jp_c","jp_zl","jp_wfpmr","jp_zlt","jp_wnt"],fa),"jp_c"!==window.google_top_experiment){N(window,"message",Hd);window.google_top_js_status=3;var bc={0:"google_loc_request",1:Gd},cc=[],Na;for(Na in bc)cc.push(Na+"="+bc[Na]);top.postMessage(cc.join("\n"),"*")}}else window.google_top_js_status=2}else window.google_top_js_status=
1}var dc=window.google_ad_output;void 0!==window.google_always_use_delayed_impressions_experiment||dc&&"html"!=dc||(window.google_always_use_delayed_impressions_experiment=O(["C","E"],ha));var Oa;if(!(Oa=!1===window.google_enable_async)){var Pa;var ec=navigator.userAgent;ld.test(ec)?Pa=!1:(void 0!==window.google_async_for_oa_experiment||!md.test(navigator.userAgent)||ld.test(navigator.userAgent)||(window.google_async_for_oa_experiment=O(["E","C"],ga)),Pa=md.test(ec)?"E"===window.google_async_for_oa_experiment:
!0);Oa=!Pa||window.google_container_id||window.google_ad_output&&"html"!=window.google_ad_output}if(Oa)a.google_loader_used="sb",a.google_start_time=t,Fd(a,a),document.write(Dd(a.google_ad_client)+Ad());else{if(zd){var fc=a.google_ad_client,Id=navigator;if(Aa&&a&&fc&&Id){var gc=a.document,ia=gc.createElement("script"),Jd=od(fc);ia.async=!0;ia.type="text/javascript";ia.src=Qc("pagead2.googlesyndication.com","/pub-config/"+Jd+".js");var hc=gc.getElementsByTagName("script")[0];hc.parentNode.insertBefore(ia,
hc)}}a.google_unique_id?++a.google_unique_id:a.google_unique_id=1;var l={};null==a.google_ad_client&&ed(a,l)&&(l.google_loader_features_used=2048);dd(a,l);l.google_loader_used="sa";gd(a);var ic=F("script"),Qa,ja;a:{try{var L=a.top.google_pubvars_reuse_experiment;if("undefined"!==typeof L){ja=L;break a}L=O(["C","E"],Ba)||null;a.top.google_pubvars_reuse_experiment=L;if(a.top.google_pubvars_reuse_experiment===L){ja=L;break a}}catch(Zd){}ja=null}if("E"===ja){var Kd=null!=l.google_ad_client,Ld=null!=l.google_ad_width,
Md=null!=l.google_ad_height,jc=rd(a);if(jc){for(var Ra=0;Ra<qd.length;Ra++){var Sa=qd[Ra];null!=l[Sa]&&(jc[Sa]=l[Sa])}var S=rd(a);if(S){var kc=S.google_ad_width,lc=S.google_ad_height,Ta=S.google_ad_format;if(kc&&lc&&Ta){var ka,Ua=Ta&&Ta.match(/(\d+)x(\d+)/);ka=Ua?{width:Ua[1],height:Ua[2]}:null;!ka||ka.width==kc&&ka.height==lc||delete S.google_ad_format}}}var Va=rd(a);if(Va)for(var Wa=0;Wa<qd.length;Wa++){var la=qd[Wa];null==l[la]&&null!=Va[la]&&(l[la]=Va[la])}var Nd=null!=l.google_ad_client,Od=null!=
l.google_ad_width,Pd=null!=l.google_ad_height;Qa=[Kd?"c2":Nd?"c1":"c0",Ld?"w2":Od?"w1":"w0",Md?"h2":Pd?"h1":"h0"].join()}var r={},Qd=l.google_ad_height;r.width='"'+l.google_ad_width+'"';r.height='"'+Qd+'"';r.frameborder='"0"';r.marginwidth='"0"';r.marginheight='"0"';r.vspace='"0"';r.hspace='"0"';r.allowtransparency='"true"';r.scrolling='"no"';r.allowfullscreen='"true"';r.onload='"'+jd+'"';for(var ma,mc=a.document,T=r.id,Rd=0;!T||mc.getElementById(T);)T="aswift_"+Rd++;r.id=T;r.name=T;var nc=l.google_ad_width,
oc=l.google_ad_height,Xa=V.A,pc=Xa.j,qc=Xa.i,rc=l.google_active_plles=l.google_active_plles||[];Lb(Rb(a),pc)?rc.push(pc):Lb(Rb(a),qc)&&rc.push(qc);nd=Lb(Rb(a),Xa.i);var na=["<iframe"],oa;for(oa in r)r.hasOwnProperty(oa)&&Kb(na,oa+"="+r[oa]);var Ya="left:0;position:absolute;top:0;";nd&&(Ya=Ya+"width:"+nc+"px;height:"+oc+"px;");na.push('style="'+Ya+'"');na.push("></iframe>");var sc=r.id,tc="border:none;height:"+oc+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+nc+"px;background-color:transparent";
mc.write(['<ins id="',sc+"_expand",'" style="display:inline-table;',tc,'"><ins id="',sc+"_anchor",'" style="display:block;',tc,'">',na.join(" "),"</ins></ins>"].join(""));ma=r.id;var pa;pa=Ed(l)?O(["c","e"],za):null;Fd(a,l,"e"==pa);var Sd=fd(l),M=null,Za=O(["C","E"],Da);if("E"==Za){a:{try{if(window.JSON&&window.JSON.stringify&&window.encodeURIComponent){var $a=encodeURIComponent(window.JSON.stringify(l)),ab;if(Xc)ab=n.btoa($a);else{for(var D=[],uc=0,bb=0;bb<$a.length;bb++){for(var U=$a.charCodeAt(bb);255<
U;)D[uc++]=U&255,U>>=8;D[uc++]=U}if(!Wc){Wc={};for(var qa=0;65>qa;qa++)Wc[qa]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(qa)}for(var ra=Wc,vc=[],E=0;E<D.length;E+=3){var wc=D[E],xc=E+1<D.length,yc=xc?D[E+1]:0,zc=E+2<D.length,Ac=zc?D[E+2]:0,Td=wc>>2,Ud=(wc&3)<<4|yc>>4,Bc=(yc&15)<<2|Ac>>6,Cc=Ac&63;zc||(Cc=64,xc||(Bc=64));vc.push(ra[Td],ra[Ud],ra[Bc],ra[Cc])}ab=vc.join("")}M=ab;break a}Eb(Yb,"sblob",{json:window.JSON?1:0,eURI:window.encodeURIComponent?1:0},!0,void 0,void 0)}catch(Vd){Q.o("sblob",
Vd,void 0,void 0)}M=""}M||(M="{X}")}else"C"==Za&&(M="{C}");var Wd=Dd(l.google_ad_client),Dc=(new Date).getTime(),Ec=a.google_top_experiment,cb=a.google_async_for_oa_experiment;cb&&(a.google_async_for_oa_experiment=void 0);var Fc=a.google_always_use_delayed_impressions_experiment,Xd=["<!doctype html><html><body>",Wd,"<",ic,">",Sd,"google_show_ads_impl=true;google_unique_id=",a.google_unique_id,';google_async_iframe_id="',ma,'";google_start_time=',t,";",Za?'google_pub_vars = "'+M+'";':"",Qa?'google_pubvars_reuse_experiment_result = "'+
Qa+'";':"",Ec?'google_top_experiment="'+Ec+'";':"",cb?'google_async_for_oa_experiment="'+cb+'";':"",Fc?'google_always_use_delayed_impressions_experiment="'+Fc+'";':"",pa?'google_append_as_for_format_override="'+pa+'";':"","google_bpp=",Dc>t?Dc-t:1,";google_async_rrc=0;</",ic,">",Ad(),"</body></html>"].join("");(a.document.getElementById(ma)?xd:yd)(Bd(a,ma,Xd,!0))}}});}).call(this);

/*
     FILE ARCHIVED ON 16:36:05 Sep 24, 2015 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 04:59:46 Sep 10, 2018.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  LoadShardBlock: 343.542 (18)
  esindex: 0.046 (5)
  CDXLines.iter: 406.649 (12)
  PetaboxLoader3.datanode: 258.479 (19)
  exclusion.robots: 1.583 (5)
  exclusion.robots.policy: 1.499 (5)
  RedisCDXSource: 15.185 (5)
  PetaboxLoader3.resolve: 34.686
  load_resource: 59.54
*/